import React,{useState}from'react';import{Link,useParams}from'react-router-dom';import{useAppStore}from'../state/appStore';
const tracks=[['web','🌐 Web Foundations','HTML, CSS, JavaScript, HTTP and browsers'],['git','🌱 Git','Hashes, objects, commits and merges'],['db','🗃️ Databases','Pages, records, indexes and SQL'],['server','🛰️ Servers','Sockets, HTTP and observability'],['python','🐍 Python','Programming fundamentals']];
const projects=[['http','Build an HTTP Server','Parse requests, route paths and return responses.'],['git-client','Build Git','Implement objects, refs, commits and merges.'],['mini-db','Build a Database','Implement pages, records, indexes and transactions.'],['shell','Build a Shell','Commands, processes, pipes, redirection and signals.'],['compiler','Build a Compiler','Lexer, parser, type checker, bytecode and VM.']];
function Page({title,kicker,text,children}:{title?:string;kicker:string;text:string;children:React.ReactNode}){return <div className="product-page"><header className="topbar"><Link to="/">← LearnBuild</Link><Link className="button" to="/auth">Account</Link></header><main><span className="eyebrow">{kicker}</span>{title&&<h1>{title}</h1>}<p className="lead">{text}</p>{children}</main></div>}
export function AuthExperience(){const[email,setEmail]=useState('');const[signup,setSignup]=useState(false);return <div className="auth-page"><div className="auth-card"><span className="eyebrow">LEARNBUILD ACCOUNT</span><h1>{signup?'Create your learning account.':'Welcome back.'}</h1><p>Save XP, streaks, lessons and projects across devices.</p><button>Continue with Google</button><button>Continue with Apple</button><div className="or">or</div><input value={email}onChange={e=>setEmail(e.target.value)}placeholder="Email address"/><input type="password"placeholder="Password"/><button className="primary">{signup?'Create account':'Sign in'}</button><button className="linklike"onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'Need an account? Sign up'}</button></div></div>}
export function LearningCatalog(){return <Page title="Choose your next skill" kicker="LEARNING CATALOG" text="Follow a roadmap, practice between lessons and unlock projects as your understanding grows."><div className="grid">{tracks.map(t=><article key={t[0]}><h3>{t[1]}</h3><p>{t[2]}</p><Link to={'/course/'+t[0]}>Open track →</Link></article>)}</div></Page>}
export function CoursePage(){const{id}=useParams();const track=tracks.find(t=>t[0]===id)||tracks[0];return <Page title={track[1]} kicker="COURSE ROADMAP" text={track[2]}><div className="lesson-list">{Array.from({length:12},(_,i)=><Link className="lesson-row"key={i}to={`/lesson/${track[0]}/${i+1}`}><b>{i+1}</b><span><strong>{['Mental model','Read the source','Make a prediction','Inspect the bytes','Build the smallest version','Debug a failure','Add a feature','Write a test','Measure it','Explain it','Ship it','Checkpoint'][i]}</strong><small>10–20 min · +25 XP</small></span><span>→</span></Link>)}</div></Page>}
export function LessonExperience(){const{track,id}=useParams();const{complete}=useAppStore();const[answer,setAnswer]=useState('');const[done,setDone]=useState(false);return <Page kicker={`LESSON ${id}`} title={`Understand ${track?.toUpperCase()||'THE SYSTEM'}`} text="Predict, inspect, build, explain."><div className="lesson-card"><h2>Build a mental model</h2><p>What happens first? What state changes? What data crosses the boundary? Write a prediction before revealing the explanation.</p><textarea value={answer}onChange={e=>setAnswer(e.target.value)}placeholder="My prediction..."/><details><summary>Reveal explanation</summary><p>Engineering understanding comes from making a model, testing it against evidence and updating it when reality disagrees.</p></details><button className="primary"onClick={()=>{complete(`${track}-${id}`);setDone(true)}}>{done?'Completed +25 XP':'Mark lesson complete'}</button></div></Page>}
export function ProfilePage(){const{progress}=useAppStore();return <Page kicker="BUILDER PROFILE" title="Your engineering record" text="Track what you understand, what you practiced and what you built."><div className="grid"><article><b>Level</b><h2>{progress.level}</h2></article><article><b>XP</b><h2>{progress.xp}</h2></article><article><b>Lessons</b><h2>{progress.completed.length}</h2></article></div></Page>}
export function PracticePage(){const{complete}=useAppStore();const[correct,setCorrect]=useState(false);return <Page kicker="DAILY PRACTICE" title="Practice the edges" text="Questions are designed to expose gaps, not reward guessing."><div className="lesson-card"><h2>Why does DNS happen before HTTP?</h2>{['To resolve a hostname to an IP address','To encrypt the request','To compile JavaScript','To store cookies'].map((x,i)=><button key={x}onClick={()=>{setCorrect(i===0);if(i===0)complete('dns-practice',15)}}>{x}</button>)}{correct&&<p><strong>Correct.</strong> DNS maps a name to an address so the client can locate the server.</p>}</div></Page>}
export function ChallengeBank(){return <Page kicker="CHALLENGE BANK" title="Practice the sharp edges" text="Debugging, reasoning, implementation and systems questions."><div className="grid">{Array.from({length:20},(_,i)=><article key={i}><span className="eyebrow">CHALLENGE {i+1}</span><h3>{['Predict the packet','Fix a parser','Trace a commit','Repair an index','Find the race'][i%5]}</h3><p>Hints, tests and explanation after submission.</p><Link to="/practice">Attempt →</Link></article>)}</div></Page>}
export function ProjectsPage(){return <Page kicker="PROJECT STUDIO" title="Build systems, not tutorials" text="Projects combine skills into something you can explain, test and ship."><div className="grid">{projects.map(p=><article key={p[0]}><span className="eyebrow">CAPSTONE</span><h2>{p[1]}</h2><p>{p[2]}</p><Link to={'/projects/'+p[0]}>Open workspace →</Link></article>)}</div></Page>}
export function ProjectWorkspace(){const{id}=useParams();const p=projects.find(x=>x[0]===id)||projects[0];return <Page kicker="PROJECT WORKSPACE" title={p[1]} text={p[2]}><div className="grid"><article><h3>1. Model</h3><p>Define inputs, outputs, state and failure modes.</p></article><article><h3>2. Build</h3><p>Implement the smallest version and keep feedback tight.</p></article><article><h3>3. Test</h3><p>Write tests, then deliberately break the system.</p></article><article><h3>4. Ship</h3><p>Package, observe, document and publish.</p></article></div><Link className="button primary"to="/practice">Start checkpoint</Link></Page>}
export function GenericPage({title,kicker,text,cards}:{title:string;kicker:string;text:string;cards:string[]}){return <Page title={title}kicker={kicker}text={text}><div className="grid">{cards.map(c=><article key={c}><h3>{c}</h3><p>Interactive experience with explanations, experiments, checkpoints and earned progress.</p><Link to="/practice">Open →</Link></article>)}</div></Page>}
