import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles/platform.css';

type Lesson={id:string;track:string;title:string;level:number;mins:number;xp:number;body:string;steps:string[]};
type Project={id:string;title:string;track:string;level:string;desc:string;skills:string[];xp:number};
const tracks=[
{id:'web',name:'Web Foundations',icon:'◈',color:'#6ee7ff',desc:'Rebuild the web from packets to pixels.'},
{id:'js',name:'JavaScript',icon:'JS',color:'#ffd66e',desc:'Language, runtime, DOM, async and tooling.'},
{id:'python',name:'Python',icon:'🐍',color:'#77e0a0',desc:'Build useful programs from first principles.'},
{id:'git',name:'Git & Collaboration',icon:'⑂',color:'#ff8a7a',desc:'Understand version control by rebuilding it.'},
{id:'db',name:'Databases',icon:'▤',color:'#b69cff',desc:'Pages, indexes, queries, WAL and transactions.'},
{id:'server',name:'Servers & Networking',icon:'⌁',color:'#7fb4ff',desc:'Sockets, HTTP, proxies, TLS, DNS and monitoring.'},
{id:'linux',name:'Linux & Containers',icon:'▣',color:'#d4e18f',desc:'Processes, filesystems, namespaces and containers.'},
{id:'cloud',name:'Cloud & Hosting',icon:'☁',color:'#82e7da',desc:'Ship websites, APIs, domains, CI/CD and scale.'},
{id:'build',name:'Compilers & Languages',icon:'λ',color:'#f1a7ff',desc:'Lexers, parsers, ASTs, bytecode and VMs.'},
{id:'security',name:'Security & Reliability',icon:'◉',color:'#ff9eae',desc:'Threat models, auth, secrets, testing and resilience.'}
];
const seedLessons:Lesson[] = tracks.flatMap((t,ti)=>Array.from({length:20},(_,i)=>({id:`${t.id}-${i+1}`,track:t.id,title:`${t.name}: ${['Mental model','First principles','Inspecting the pieces','Build a tiny version','State and data','Errors and recovery','Inputs and outputs','Testing behavior','Performance basics','Debugging patterns','Interfaces','Persistence','Security boundaries','Automation','Observability','Deployment','Failure modes','Tradeoffs','Capstone planning','Ship it'][i]}`,level:Math.floor(i/5)+1,mins:8+(i%5)*3,xp:15+(i%6)*5,body:`You are learning ${t.name.toLowerCase()} by rebuilding a small, understandable version of a real system. Lesson ${i+1} uses concrete experiments, short code, predictions, and a build step.`,steps:[`Learn the core idea behind ${t.name.toLowerCase()}.`,`Predict what the system should do before running code.`,`Build a tiny working version.`,`Break it on purpose, inspect the failure, then repair it.`]})));
const projects:Project[]=[
{id:'p1',title:'Build Your Own Git',track:'git',level:'Intermediate',desc:'Create hashes, blobs, trees, commits and a tiny CLI.',skills:['SHA-1','files','CLI','DAGs'],xp:500},
{id:'p2',title:'Mini Database Engine',track:'db',level:'Advanced',desc:'Implement pages, a B-tree index, WAL and transactions.',skills:['storage','indexes','WAL','transactions'],xp:900},
{id:'p3',title:'HTTP Server From Scratch',track:'server',level:'Intermediate',desc:'Serve static files, parse HTTP and add routing, logs and keep-alive.',skills:['TCP','HTTP','routing','logs'],xp:600},
{id:'p4',title:'Static Site + Custom Domain',track:'cloud',level:'Beginner',desc:'Build and deploy a site with HTTPS, DNS, CI and previews.',skills:['GitHub Pages','DNS','CI/CD','HTTPS'],xp:350},
{id:'p5',title:'Tiny Programming Language',track:'build',level:'Advanced',desc:'Write a lexer, parser, AST evaluator and bytecode VM.',skills:['lexer','parser','AST','VM'],xp:1000},
{id:'p6',title:'Secure Login System',track:'security',level:'Advanced',desc:'Model sessions, hashing, cookies, CSRF and rate limits safely.',skills:['auth','sessions','cookies','threat model'],xp:850},
];
function useStore(){const[key,setKey]=useState(0);const get=(k:string,d:any)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};const set=(k:string,v:any)=>{localStorage.setItem(k,JSON.stringify(v));setKey(x=>x+1)};return{key,get,set}}
function App(){const s=useStore();const[user,setUser]=useState<any>(()=>s.get('lb_user',null));const[page,setPage]=useState('home');const[query,setQuery]=useState('');const[track,setTrack]=useState('all');const[selected,setSelected]=useState<Lesson|null>(null);const[toast,setToast]=useState('');
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)}},[toast]);
const progress=s.get('lb_progress',{});const xp=s.get('lb_xp',0);const streak=s.get('lb_streak',1);
const filtered=useMemo(()=>seedLessons.filter(l=>(track==='all'||l.track===track)&&(!query||`${l.title} ${l.track}`.toLowerCase().includes(query.toLowerCase()))),[query,track]);
const complete=(l:Lesson)=>{const p={...progress,[l.id]:true};s.set('lb_progress',p);s.set('lb_xp',xp+l.xp);setToast(`+${l.xp} XP · lesson complete`)};
const nav=(p:string)=>{setSelected(null);setPage(p)};
if(!user)return <Auth onDone={u=>{setUser(u);s.set('lb_user',u);setToast('Welcome to LearnBuild')}}/>;
return <div className='shell'><header className='top'><button className='brand' onClick={()=>nav('home')}><span className='brandmark'>LB</span><span>Learn<span>Build</span></span></button><div className='search'><span>⌕</span><input placeholder='Search lessons, projects, concepts...' value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>nav('learn')}/></div><div className='topstats'><b>🔥 {streak}</b><b>⚡ {xp} XP</b><button className='avatar' onClick={()=>nav('profile')}>{(user.name||'U')[0].toUpperCase()}</button></div></header><div className='layout'><aside className='side'><div className='navgroup'><button className={page==='home'?'active':''} onClick={()=>nav('home')}>⌂ Home</button><button className={page==='learn'?'active':''} onClick={()=>nav('learn')}>▤ Learn</button><button className={page==='practice'?'active':''} onClick={()=>nav('practice')}>⚡ Practice</button><button className={page==='projects'?'active':''} onClick={()=>nav('projects')}>◫ Projects</button><button className={page==='hosting'?'active':''} onClick={()=>nav('hosting')}>☁ Hosting Lab</button></div><div className='side-label'>EXPLORE</div><button onClick={()=>nav('tracks')}>◎ Tracks</button><button onClick={()=>nav('community')}>♟ Community</button><button onClick={()=>nav('leaderboard')}>♛ Leaderboard</button><div className='side-label'>YOUR SPACE</div><button onClick={()=>nav('profile')}>◉ Profile</button><button onClick={()=>nav('settings')}>⚙ Settings</button><div className='sidebottom'><div className='mini-card'><strong>{Math.round(Object.values(progress).filter(Boolean).length/seedLessons.length*100)}%</strong><span>journey complete</span></div></div></aside><main className='main'>{page==='home'&&<Home nav={nav} user={user} progress={progress} xp={xp} lessons={filtered}/>} {page==='learn'&&<Learn lessons={filtered} track={track} setTrack={setTrack} progress={progress} onOpen={setSelected}/>} {page==='tracks'&&<Tracks onSelect={t=>{setTrack(t);nav('learn')}}/>} {page==='projects'&&<Projects/>} {page==='practice'&&<Practice onToast={setToast}/>} {page==='hosting'&&<Hosting onToast={setToast}/>} {page==='community'&&<Community/>} {page==='leaderboard'&&<Leaderboard/>} {page==='profile'&&<Profile user={user} progress={progress} xp={xp}/>} {page==='settings'&&<Settings user={user} logout={()=>{localStorage.removeItem('lb_user');setUser(null)}}/>}</main></div>{selected&&<LessonModal lesson={selected} done={!!progress[selected.id]} onClose={()=>setSelected(null)} onComplete={complete}/>} {toast&&<div className='toast'>{toast}</div>}</div>}
function Auth({onDone}:{onDone:(u:any)=>void}){const[mode,setMode]=useState<'login'|'signup'>('signup');const[name,setName]=useState('');const[email,setEmail]=useState('');return <div className='authpage'><div className='authhero'><div className='orb o1'/><div className='orb o2'/><span className='eyebrow'>LEARN BY BUILDING</span><h1>Don't just use technology.<br/><em>Rebuild it.</em></h1><p>Learn how the tools you love actually work—from packets and processes to databases, Git, servers and the cloud.</p><div className='quote'>“Every lesson gives you something real to make.”</div></div><div className='authcard'><div className='authlogo'><span className='brandmark'>LB</span> LearnBuild</div><h2>{mode==='signup'?'Create your account':'Welcome back'}</h2><p className='muted'>{mode==='signup'?'Your progress syncs across devices when connected to a backend.':'Continue your learning journey.'}</p>{mode==='signup'&&<input placeholder='Display name' value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder='Email address' value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder='Password' type='password'/><button className='primary wide' onClick={()=>onDone({name:name||email.split('@')[0]||'Builder',email})}>{mode==='signup'?'Create account':'Sign in'}</button><div className='or'><span>or continue with</span></div><div className='oauth'><button onClick={()=>onDone({name:'Google Builder',email:'google@example.com'})}>G&nbsp; Google</button><button onClick={()=>onDone({name:'Apple Builder',email:'apple@example.com'})}> Apple</button></div><small>Demo mode works locally. Add Supabase environment variables for production email/password, Google and Apple OAuth.</small><button className='link' onClick={()=>setMode(mode==='signup'?'login':'signup')}>{mode==='signup'?'Already have an account? Sign in':'Need an account? Sign up'}</button></div></div>}
function Home({nav,user,progress,xp,lessons}:{nav:any;user:any;progress:any;xp:number;lessons:Lesson[]}){const pct=Math.round(Object.values(progress).filter(Boolean).length/seedLessons.length*100);return <><section className='hero'><div><span className='eyebrow'>WELCOME BACK, {String(user.name||'BUILDER').toUpperCase()}</span><h1>Build your way<br/><span>into understanding.</span></h1><p>Short lessons. Real code. Big projects. Pick a track and start making.</p><div className='actions'><button className='primary' onClick={()=>nav('learn')}>Continue learning →</button><button className='ghost' onClick={()=>nav('projects')}>Browse projects</button></div></div><div className='hero-grid'><div className='glass'><strong>{pct}%</strong><span>journey</span><i><b style={{width:`${pct}%`}}/></i></div><div className='glass'><strong>{xp}</strong><span>XP earned</span></div><div className='glass'><strong>10</strong><span>career tracks</span></div><div className='glass'><strong>200</strong><span>core lessons</span></div></div></section><div className='sectionhead'><div><span className='eyebrow'>PICK UP WHERE YOU LEFT OFF</span><h2>Today's path</h2></div><button className='link' onClick={()=>nav('learn')}>See all lessons →</button></div><div className='lessonrow'>{lessons.slice(0,4).map(l=><LessonCard key={l.id} l={l} done={!!progress[l.id]}/>)}</div><div className='sectionhead'><div><span className='eyebrow'>LEARNING BY MAKING</span><h2>Featured projects</h2></div><button className='link' onClick={()=>nav('projects')}>All projects →</button></div><div className='projectgrid'>{projects.slice(0,3).map(p=><ProjectCard p={p} key={p.id}/>)}</div></>}
function Learn({lessons,track,setTrack,progress,onOpen}:{lessons:Lesson[];track:string;setTrack:any;progress:any;onOpen:any}){return <><section className='pageintro'><span className='eyebrow'>LEARNING LIBRARY</span><h1>Choose a path. Build a system.</h1><p>Every track has beginner foundations, guided builds, practice and a capstone.</p></section><div className='filters'>{[['all','All tracks'],...tracks.map(t=>[t.id,t.name])].map(x=><button key={x[0]} className={track===x[0]?'chip active':'chip'} onClick={()=>setTrack(x[0])}>{x[1]}</button>)}</div><div className='lessonlist'>{lessons.map(l=><LessonCard key={l.id} l={l} done={!!progress[l.id]} big onOpen={()=>onOpen(l)}/>)}</div></>}
function Tracks({onSelect}:{onSelect:any}){return <><section className='pageintro'><span className='eyebrow'>10 WORLDS · 200 CORE LESSONS</span><h1>Your technical skill tree.</h1><p>Follow one path or mix them. The curriculum is designed to compound.</p></section><div className='trackgrid'>{tracks.map(t=><button className='tracktile' key={t.id} onClick={()=>onSelect(t.id)}><span style={{color:t.color}}>{t.icon}</span><h3>{t.name}</h3><p>{t.desc}</p><div><b>20 lessons</b><span>4 levels</span></div></button>)}</div></>}
function LessonCard({l,done,big,onOpen}:{l:Lesson;done:boolean;big?:boolean;onOpen?:()=>void}){return <div className={`lessoncard ${big?'big':''}`} onClick={onOpen}><div className='lessonicon'>{done?'✓':'+'}</div><div className='lessonbody'><div className='muteline'><span>{tracks.find(t=>t.id===l.track)?.name}</span><span>Level {l.level}</span><span>{l.mins} min</span></div><h3>{l.title}</h3><p>{l.body}</p></div><div className='lessonxp'>+{l.xp} XP</div></div>}
function LessonModal({lesson,done,onClose,onComplete}:{lesson:Lesson;done:boolean;onClose:any;onComplete:any}){return <div className='modalback' onClick={onClose}><div className='modal' onClick={e=>e.stopPropagation()}><button className='close' onClick={onClose}>×</button><span className='eyebrow'>{tracks.find(t=>t.id===lesson.track)?.name} · LEVEL {lesson.level}</span><h2>{lesson.title}</h2><p className='lede'>{lesson.body}</p><div className='steps'>{lesson.steps.map((s,i)=><div key={i}><b>{i+1}</b><span>{s}</span></div>)}</div><div className='sandbox'><div className='editorhead'><span>Playground</span><span>JavaScript · editable</span></div><textarea defaultValue={`// Predict → edit → run → explain\nconst answer = 2 + 2;\nconsole.log(answer);`}/><div className='runline'><button className='primary' onClick={()=>onComplete(lesson)}>{done?'Completed ✓':'Complete lesson +' + lesson.xp + ' XP'}</button><span>Progress saves on this device.</span></div></div></div></div>}
function ProjectCard({p}:{p:Project}){return <div className='projectcard'><div className='projecttop'><span>{tracks.find(t=>t.id===p.track)?.icon}</span><small>{p.level}</small></div><h3>{p.title}</h3><p>{p.desc}</p><div className='tags'>{p.skills.map(s=><span key={s}>{s}</span>)}</div><div className='projectfoot'><b>+{p.xp} XP</b><button className='ghost small'>Open studio →</button></div></div>}
function Projects(){return <><section className='pageintro'><span className='eyebrow'>PROJECT STUDIO</span><h1>Make something worth showing.</h1><p>Projects are bigger than lessons. Plan, build, test, deploy and write a README.</p></section><div className='projectgrid'>{projects.map(p=><ProjectCard p={p} key={p.id}/>)}</div><div className='studio'><div><span className='eyebrow'>YOUR WORKSPACE</span><h2>Project Studio</h2><p>Notebook + editor + terminal + test panel in one place.</p></div><div className='studio-tabs'><span>Files</span><span className='active'>Editor</span><span>Terminal</span><span>Tests</span></div><pre>{`learnbuild/\n├─ README.md\n├─ src/\n│  ├─ main.js\n│  └─ tests.js\n└─ notes/\n   └─ design.md`}</pre></div></>}
function Practice({onToast}:{onToast:any}){const[q,setQ]=useState(0);const qs=['What does DNS translate?','Which structure usually gives O(log n) lookup in a balanced tree?','What does a TCP socket provide?'];const a=['domain names to IP addresses','an indexed tree','a reliable byte stream'];return <><section className='pageintro'><span className='eyebrow'>DAILY PRACTICE</span><h1>Train recall, not just recognition.</h1><p>Fast questions keep ideas available when you start a project.</p></section><div className='quiz'><span className='eyebrow'>QUESTION {q+1} / 3</span><h2>{qs[q]}</h2><div className='answers'>{a.map((x,i)=><button key={i} onClick={()=>{onToast(i===q?'+10 XP · correct':'Keep experimenting — review the concept');setQ((q+1)%3)}}>{x}</button>)}</div></div></>}
function Hosting({onToast}:{onToast:any}){const[step,setStep]=useState(1);const steps=['Static site','Domain','HTTPS','CI/CD','Logs','Health checks','Containers','Scale'];return <><section className='pageintro'><span className='eyebrow'>HOSTING LAB</span><h1>Learn deployment by actually deploying.</h1><p>A guided simulator that teaches what hosting services do before you pay for them.</p></section><div className='hostlab'><div className='hoststeps'>{steps.map((x,i)=><button className={step===i+1?'active':''} onClick={()=>setStep(i+1)} key={x}><b>{i+1}</b>{x}</button>)}</div><div className='hostcontent'><span className='eyebrow'>STAGE {step}</span><h2>{steps[step-1]}</h2><p>{['Turn a repository into a public website.','Map a human-friendly name to your host.','Encrypt traffic and verify certificates.','Automate build → test → deploy.','Read logs like a detective.','Know when an app is healthy.','Package repeatable services.','Handle growth without guessing.'][step-1]}</p><div className='terminal'><div>learnbuild@cloud:~$ deploy --stage {step}</div><div>✓ preflight checks passed</div><div>✓ build artifact created</div><div>✓ simulator updated</div><div className='cursor'>█</div></div><button className='primary' onClick={()=>{if(step<8)setStep(step+1);onToast('Hosting lab progress saved')}}>Complete stage →</button></div></div></>}
function Community(){return <><section className='pageintro'><span className='eyebrow'>COMMUNITY</span><h1>Learn with other builders.</h1><p>Project showcases, questions, study rooms and mentor notes.</p></section><div className='communitygrid'>{[['Build logs','Share what you made and what broke.'],['Study rooms','Small groups for weekly goals.'],['Help desk','Ask questions with code and context.'],['Showcase','Publish finished projects.']].map(x=><div className='communitycard' key={x[0]}><span>✦</span><h3>{x[0]}</h3><p>{x[1]}</p><button className='ghost small'>Explore →</button></div>)}</div></>}
function Leaderboard(){return <><section className='pageintro'><span className='eyebrow'>WEEKLY LEAGUE</span><h1>Consistency beats cramming.</h1><p>XP from lessons, practice and projects all counts.</p></section><div className='leader'><div className='row head'><span>#</span><span>Builder</span><span>Level</span><span>XP</span></div>{['Mika','Jun','Avery','Noah','You','Sam'].map((n,i)=><div className={'row '+(n==='You'?'me':'')} key={n}><span>{i+1}</span><span>◉ {n}</span><span>{12-i}</span><span>{2480-i*183}</span></div>)}</div></>}
function Profile({user,progress,xp}:{user:any;progress:any;xp:number}){const done=Object.values(progress).filter(Boolean).length;return <><div className='profilehero'><div className='bigavatar'>{(user.name||'U')[0]}</div><div><span className='eyebrow'>BUILDER PROFILE</span><h1>{user.name}</h1><p>{user.email}</p></div><button className='ghost'>Edit profile</button></div><div className='statgrid'><div><b>{xp}</b><span>XP</span></div><div><b>{done}</b><span>Lessons</span></div><div><b>8</b><span>Badges</span></div><div><b>1</b><span>Projects</span></div></div><h2 className='mt'>Achievements</h2><div className='badges'>{['First commit','7 day streak','Bug hunter','Ship it','Database builder','Cloud pilot','Security minded','Capstone'].map((x,i)=><div className={i<3?'badge earned':'badge'} key={x}><span>{['◆','🔥','⚙','🚀','▤','☁','◉','★'][i]}</span><b>{x}</b><small>{i<3?'Unlocked':'Locked'}</small></div>)}</div></>}
function Settings({user,logout}:{user:any;logout:any}){return <><section className='pageintro'><span className='eyebrow'>SETTINGS</span><h1>Your LearnBuild account.</h1></section><div className='settings'><label>Display name<input defaultValue={user.name}/></label><label>Email<input defaultValue={user.email}/></label><label>Theme<select defaultValue='dark'><option>dark</option><option>light</option><option>system</option></select></label><div className='settingline'><div><b>Local progress</b><span>Stored instantly in your browser.</span></div><button className='ghost'>Export data</button></div><div className='settingline danger'><div><b>Sign out</b><span>Remove this local session.</span></div><button className='ghost' onClick={logout}>Sign out</button></div></div></>}
const root=createRoot(document.getElementById('root')!);root.render(<App/>);
